---
name: Run unit tests

on:
  push:

jobs:
  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": ["send_to_dock"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Release"]
              },
              "test": {
                "packages-select": ["send_to_dock"]
              }
            }
